# ============================================
# application.yml - AUTH SERVICE
# ============================================

spring:
  application:
    name: auth-service
    
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update  # Cambiar a 'update' en producción

# Puerto del microservicio
server:
  port: 8080

# ✅ AGREGAR ESTA SECCIÓN - DESHABILITAR EUREKA
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

# ✅ CONFIGURACIÓN DE MICROSERVICIOS
services:
  academic:
    url: http://localhost:8081
  payment:
    url: http://localhost:8082

# Configuración de Feign Client
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000

# Configuración de logging para debugging
logging:
  level:
    com.school.auth.clients: DEBUG
    feign: DEBUG
    com.netflix.discovery: OFF  # ✅ AGREGAR - Silenciar logs de Eureka

# Configuración de Seguridad JWT
security:
  jwt:
    secret-key: mySecretKey
    expiration-time: 86400000

# Circuit Breaker (opcional - Resilience4j)
resilience4j:
  circuitbreaker:
    instances:
      academic-service:
        sliding-window-size: 10
        failure-rate-threshold: 50

# Configuración de CORS
cors:
  allowed-origins: http://localhost:4200

# ✅ AGREGAR - Health endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always